# -*- coding: utf-8 -*-
"""M.Jamshidbek

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TnZ1WLpNP0b5psLT9vplLP3Q33CS01ds
"""

import numpy as np

# 1. Massiv yaratish
array_1d = np.array([1, 2, 3, 4, 5,])
array_2d = np.array([[1, 2, 3,], [ 4, 5, 6]])

# 2. Matematik operatsiyalar
sum_array = np.sum(array_1d)
mean_array = np.mean(array_1d)
product_array = np.prod(array_1d)

print("1D Massiv:", array_1d)
print("2D massiv:\n", array_2d)
print(" Massivlar yig'indisi: ", sum_array)
print("O'rtacha:", mean_array)
print("ko'paytma:", product_array)



import pandas as pn

# 1. DataFrame yaratish
data = {
    'Ism' : ['Jamshidbek', 'Vali', 'Sardor','Bekzod', 'Mamurjon', 'Ortiqmirzo', 'Abdurahmon', 'Rahimberdi', 'Biloliddin','Samandar'],
    'Yoshi': [25, 30, 22, 25, 23, 19, 21, 27, 18, 22],
    'Shahar' : ['Toshkent', 'Xorazm', 'Andijon', 'Navoiy', 'Namangan', 'Andijon', 'Fargona', 'Andijon', 'Fargona', 'Fargona']

}
df = pn.DataFrame(data)

#2. Ma'lumotlarni ko'rish
print(df)

#3. Filtrlash
young_people = df[df['Yoshi']< 30]
print("30 yoshdan kichiklar:\n",young_people)

#4. O'zgartirish
df['Yoshi'] += 1 # Har bir shaxsning yoshini 1 ga oshirish
print("Yangilangan DataFrame :\n",df)

"""# New section"""